export const FETCH_ALL_USER_STORIES = "FETCH_ALL_USER_STORIES";
export const CLEAR_ALL_USER_STORIES = "CLEAR_ALL_USER_STORIES";
export const FETCH_ALL_USER_POST = "FETCH_ALL_USER_POST";
export const CLEAR_ALL_USER_POST = "CLEAR_ALL_USER_POST";
